"""empty message

Revision ID: c697bc26e963
Revises: 
Create Date: 2022-01-05 09:38:33.713047

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c697bc26e963'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('dca_schedule',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('dca_instance', sa.String(length=100), nullable=True),
    sa.Column('exchange_id', sa.String(length=100), nullable=True),
    sa.Column('api_key', sa.PickleType(), nullable=True),
    sa.Column('api_secret', sa.PickleType(), nullable=True),
    sa.Column('api_uid', sa.PickleType(), nullable=True),
    sa.Column('api_passphrase', sa.PickleType(), nullable=True),
    sa.Column('dca_frequency', sa.String(length=100), nullable=True),
    sa.Column('trading_pair', sa.String(length=100), nullable=True),
    sa.Column('dca_lastRun', sa.DateTime(), nullable=True),
    sa.Column('dca_firstRun', sa.DateTime(), nullable=True),
    sa.Column('dca_nextRun', sa.DateTime(), nullable=True),
    sa.Column('dca_budget', sa.Integer(), nullable=True),
    sa.Column('isActive', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('name', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('dca_schedule')
    # ### end Alembic commands ###
